"""
2025-07-30

Calculate the Sinkhorn divergence between the distributions of feature indices
of observed records (training dataset) and those of generated ground-motion data.
The Sinkhorn divergence is calculated for each epoch, and the analysis results are saved in a single CSV file with a shape of (N, 2).
N is the number of candidate models (i.e., models trained with different epochs);
the first column lists the epochs, and the second column represents the corresponding Sinkhorn divergence values.

In this script, the following calculations are processed.
    1. Compute the feature indices for observed records (training dataset).
    2. Compute the feature indices for ground-motion data generated by the CS-GMGM model at each epoch.
       These results are used to select the optimal CS-GMGM epoch.
       2.1. Generate ground-motion data by using the Generator loaded with model parameters at each epoch.
       2.2. Apply post-processing to the generated ground-motion data.
       2.3. Compute the Fourier amplitude (FFT)
       2.4. Obtain the values of feature indices.
    3. Compute the Sinkhorn divergence for each target epoch.
"""
